# Generated by Django 5.2.7 on 2025-10-27 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(blank=True, default='', max_length=64)),
                ('otp_type', models.CharField(choices=[('NONE', 'None'), ('TOTP', 'Time-based (TOTP)'), ('HOTP', 'Counter-based (HOTP)')], default='NONE', max_length=8)),
                ('hotp_counter', models.PositiveIntegerField(default=0)),
                ('issuer', models.CharField(default='PyOTP-MFA-Demo', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
